//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int EmployeeID { get; set; }
        public string User_ID { get; set; }
        public string First_name { get; set; }
        public string Surname { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
