//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table
    {
        public Order_Table()
        {
            this.Customer_Table = new HashSet<Customer_Table>();
        }
    
        public byte OrderID { get; set; }
        public string OrderRef { get; set; }
        public Nullable<byte> CustomerID { get; set; }
        public Nullable<byte> ProductID { get; set; }
    
        public virtual ICollection<Customer_Table> Customer_Table { get; set; }
        public virtual Product_Table Product_Table { get; set; }
    }
}
