//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOption
    {
        public ProductOption()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProductOptionID { get; set; }
        public string ProductOption1 { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
