//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        public Product_Table()
        {
            this.Order_Table = new HashSet<Order_Table>();
        }
    
        public byte ProductID { get; set; }
        public string ProductType { get; set; }
        public string ProductNumber { get; set; }
    
        public virtual ICollection<Order_Table> Order_Table { get; set; }
    }
}
