//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_Details
    {
        public int Quote_Details_ID { get; set; }
        public int Quote_ID { get; set; }
        public int Product_Option_ID { get; set; }
        public int Stone_ID { get; set; }
        public short Quantity { get; set; }
        public Nullable<double> Cap_Height { get; set; }
        public Nullable<double> Cap_Width { get; set; }
        public Nullable<double> Cap_Length { get; set; }
        public Nullable<double> Cap_Point { get; set; }
        public Nullable<double> Pillar_Height { get; set; }
        public Nullable<double> Pillar_Width { get; set; }
        public Nullable<double> Pillar_Length { get; set; }
        public Nullable<double> Pillar_Diameter { get; set; }
        public Nullable<double> Cap_Diameter { get; set; }
        public Nullable<double> Fireplace_Base_Width { get; set; }
        public Nullable<double> Fireplace_Base_Height { get; set; }
        public Nullable<double> Fireplace_Top_Width { get; set; }
        public Nullable<double> Fireplace_Top_Height { get; set; }
        public Nullable<double> Fireplace_Depth { get; set; }
        public decimal Item_Price { get; set; }
    
        public virtual ProductOption ProductOption { get; set; }
        public virtual Stone Stone { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
