//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slab_Table
    {
        public byte SlabID { get; set; }
        public Nullable<short> SlabSize { get; set; }
        public Nullable<decimal> SlabCost { get; set; }
    
        public virtual Stone_Type Stone_Type { get; set; }
    }
}
