//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stone_Type
    {
        public Stone_Type()
        {
            this.Cut_Cost = new HashSet<Cut_Cost>();
            this.Quotes = new HashSet<Quote>();
            this.Slabs = new HashSet<Slab>();
        }
    
        public byte StoneTypeID { get; set; }
        public string StoneType { get; set; }
    
        public virtual ICollection<Cut_Cost> Cut_Cost { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Slab> Slabs { get; set; }
    }
}
