//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stone
    {
        public Stone()
        {
            this.Slabs = new HashSet<Slab>();
            this.Products = new HashSet<Product>();
        }
    
        public int StoneId { get; set; }
        public string StoneType { get; set; }
        public Nullable<double> CostPerCube { get; set; }
        public Nullable<double> CutCost { get; set; }
    
        public virtual ICollection<Slab> Slabs { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
