//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetInStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stone
    {
        public Stone()
        {
            this.Quote_Details = new HashSet<Quote_Details>();
            this.Slabs = new HashSet<Slab>();
        }
    
        public int StoneId { get; set; }
        public string StoneType { get; set; }
        public double CostPerCube { get; set; }
        public Nullable<double> CutCost { get; set; }
    
        public virtual ICollection<Quote_Details> Quote_Details { get; set; }
        public virtual ICollection<Slab> Slabs { get; set; }
    }
}
